### ISSUE TITLE
Option to create subdirectories instead

### ISSUE THREAD

**Issue by arkon** [kashav/point#1]
Instead of making new repositories, I think it should be possible to create subdirectories in the main GitHub page repo (e.g. arkon.github.io/haiG89h/index.html).

**Comment by qasim** [comment]
This has the added benefit of users who have a domain pointing to their GitHub pages to use the shortener too, i.e. http://qas.im/haiG89h 😮

**Comment by kashav** [comment]
Oh I like this idea - not sure why I didn't think of this earlier! The only problem here is that removing URLs becomes _a little_ bit harder, since we're going to have to pull down their User Pages repo `{username}.github.{io|com}`, delete the subdirectory, and then push that. I'll play around with it - I think it can still be done.

**Comment by kashav** [comment]
Done in #4. Takes a repo name, i.e. `kshvmdn/kshvmdn.github.io` and creates the subdirectory on the default branch in that repo.
